spring:
  h2:
    console:
      enabled: true
  datasource:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      connection-test-query: SELECT 123


